name: Bug report
description: Reportar bug no Despesas da Praia
labels: [bug]
body:
  - type: input
    id: app_version
    attributes:
      label: Versão do APK
      placeholder: "Ex.: 1.0.0+1"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      placeholder: |
        1. Abra o app
        2. Cadastre uma despesa...
        3. Vá para Resumo...
    validations:
      required: true

  - type: textarea
    id: data_used
    attributes:
      label: Dados usados no teste
      description: Informe valor/categoria/pessoa/data usados
      placeholder: "R$ 120, Alimentação, Pessoa 1, 23/02/2026"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Resultado esperado
      placeholder: "O total deveria ficar em..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Resultado atual
      placeholder: "O app mostrou..."
    validations:
      required: true
